# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

env:
  GO111MODULE: on
  GOPROXY: https://goproxy.cn,direct

includes:
  color:
    dir: ./color
    taskfile: ./color/taskfile.yml

  log:
    dir: ./log
    taskfile: ./log/taskfile.yml

  oss:
    dir: ./oss
    taskfile: ./oss/taskfile.yml

  _:
    dir: ./internal
    taskfile: ./internal/taskfile.yml

tasks:
  default:
    desc: show help
    cmd: task --list-all

  githooks:
    desc: setup git hooks
    cmd: git config core.hooksPath ./internal/githooks

  setup:
    desc: setup project
    cmds:
      - task: githooks
      - go mod download

  unit:
    cmds:
      - task: color:unit
