# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

env:
  GO111MODULE: on
  GOPROXY: https://goproxy.cn,direct

tasks:
  example:color: go run ./example/color/main.go

  example:log:slog: go run ./example/log/slog/main.go

  example:log:zap: go run ./example/log/zap/main.go

  example:prettylog:
    cmds:
      - task example:log:slog | go run ../prettylog/cmd/prettylog/main.go
      - task example:log:zap | go run ../prettylog/cmd/prettylog/main.go
