// Code generated by github.com/tsingshaner/go-pkg/errors. DO NOT EDIT.
package errs

import (
	"net/http"

	"github.com/tsingshaner/go-pkg/errors"
)

var Basic = struct {
	// DatabaseQuery "M001": "Database query error"
	DatabaseQuery error
	// DatabaseConnect "M000": "Database connect error"
	DatabaseConnect error
}{
	errors.NewBasic("M001", "Database query error"),
	errors.NewBasic("M000", "Database connect error"),
}

var NotFound = struct {
	// NotFound "M040402": "User Not found"
	NotFound error
	// User "M040400": "User Not found"
	User error
}{
	errors.NewREST(http.StatusNotFound, "M040402", "User Not found"),
	errors.NewREST(http.StatusNotFound, "M040400", "User Not found"),
}

var OK = struct {
	// Login "M020000": "登录成功"
	Login error
	// Register "M020001": "注册成功"
	Register error
}{
	errors.NewREST(http.StatusOK, "M020000", "登录成功"),
	errors.NewREST(http.StatusOK, "M020001", "注册成功"),
}
