// Code generated by github.com/tsingshaner/go-pkg/errors. DO NOT EDIT.
package errs

import (
	"net/http"

	"github.com/tsingshaner/go-pkg/errors"
)

var Basic = struct {
	// DatabaseQuery "M001": "Database query error"
	DatabaseQuery error
	// DatabaseConnect "M000": "Database connect error"
	DatabaseConnect error
}{
	errors.NewBasic("M001", "Database query error"),
	errors.NewBasic("M000", "Database connect error"),
}

var NotFound = struct {
	// User "M040400": "User Not found"
	User error
}{
	errors.NewREST(http.StatusNotFound, "M040400", "User Not found"),
}

var Unauthorized = struct {
	// Login "M040100": "Username or password error"
	Login error
	// TokenExpired "M040101": "Access token expired"
	TokenExpired error
}{
	errors.NewREST(http.StatusUnauthorized, "M040100", "Username or password error"),
	errors.NewREST(http.StatusUnauthorized, "M040101", "Access token expired"),
}
