# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

env:
  GO111MODULE: on
  GOPROXY: https://goproxy.cn,direct

tasks:
  bench: go test -run=^$ -bench .

  unit:
    desc: run unit test
    cmds:
      - go test -v ./...

  coverage:
    desc: run coverage test
    cmds:
      - go tool cover -html=./coverage/cov_unit.txt -o ./coverage/cov.html
